"""
Autogenerated script for creating projects in bulk from CSV.

To be modified as needed.
"""

import csv
import os


def generate_markdown_files(csv_path):
    """
    Read a CSV file and generate Markdown files with a specific template.

    :param csv_path: Path to the input CSV file
    :param output_dir: Directory where Markdown files will be generated
    """
    output_dir = "content/projects/"
    os.makedirs(output_dir, exist_ok=True)

    with open(csv_path, "r", newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            slug = row["slug"]

            # Create the directory for the slug if it doesn't exist
            slug_dir = os.path.join(output_dir, slug)
            os.makedirs(slug_dir, exist_ok=True)

            # Prepare the Markdown content
            markdown_content = f"""---
date: "{row['date']}"
tags: ["altair"]
title: "{row['title']}"
authors: ["{row['author']}"]
courses: ["30239-A25"]
---

<a class="main link" href="{row['url']}">
<img src="feature.png" />
</a>

<div class="pdf-download rounded-md px-1 py-[1px] dark:border-primary-600">
    <a href="{row['url']}">
    <span>Download PDF</span>
    </a>
</div>

{{{{< github repo="{row.get('github').replace('https://github.com/', '')}" >}}}}


"""

            # Write the Markdown file
            markdown_path = os.path.join(slug_dir, "index.md")
            with open(markdown_path, "w", encoding="utf-8") as mdfile:
                mdfile.write(markdown_content)

            print(f"Generated: {markdown_path}")


def main():
    csv_path = "projects-a.csv"
    generate_markdown_files(csv_path)


if __name__ == "__main__":
    main()
