
[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "andes-indus"
name = "Understanding School Dropouts in Chicago: The Role of Crime and Socioeconomic Factors"
members = ["Angela López Sanchez", "Cesar Núñez", "Shahzaib Jamali"]
repo = "uchicago-2025-capp30122/30122-project-andes-indus-analytics"
youtube = "aOXfe6JOBbc"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "chiffordable"
name = "CHIffordable"
members = [
  "Daniela Ayala",
  "José Manuel Cardona",
  "Agustín Eyzaguirre",
  "María José Reyes",
]
repo = "uchicago-2025-capp30122/30122-project-chiffordable"
youtube = "ecBzrd5wgFA"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "codeconomics"
name = "Blown Away: The Rise and Fall of Businesses in the Windy City"
members = ["Hilman Hanivan", "Jorge Guerrero"]
repo = "uchicago-2025-capp30122/30122-project-codeconomics"
youtube = "TODO"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "grid-expectations"
name = "Grid Expectations"
members = ["Ethan Evans", "Ganon Evans", "Jinny Kim", "Callie Leone"]
repo = "uchicago-2025-capp30122/30122-project-flavortown"
youtube = "TODO"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "fantasticfour"
name = "Chicago Living Score Interactive Map"
members = ["Lydia Liu", "Yuri Chang", "Hamza Tariq", "Alejandro Armas"]
repo = "uchicago-2025-capp30122/30122-project-fantasticfour"
youtube = "TODO"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "menu-money"
name = "Menu Money"
members = ["Libby Seline", "Riley Morrison", "Alex McMurtry", "Getnet Dejene"]
repo = "uchicago-2025-capp30122/30122-project-gitmoney"
youtube = "TODO"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "mapademic"
name = "Mapademic"
members = ["Allen Wu", "Shiyao Wang", "Peiyu Chen", "Yue Pan"]
repo = "uchicago-2025-capp30122/30122-project-mapademic"
youtube = "bWuNfNd4cSs"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "team-dp"
name = "Exploring shifts in population and economic structure in US cities"
members = ["Ethan Caspi", "Teddy Kolios", "Liberto de Pablo", "Sophia Henn"]
repo = "uchicago-2025-capp30122/30122-project-team-dp"
youtube = "TODO"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "parksandrec"
name = "parksAndRec: Understanding the Spatial and Demographic Distribution of Open Space in Chicago"
members = [
  "José María (Chema) Gálvez Enríquez",
  "Pablo Hernandez Pedraza",
  "Raghav Mehrotra",
  "Sarah Hussain",
]
repo = "uchicago-2025-capp30122/30122-project-parksandrec"
youtube = "kKwFxz4AmzY"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "treehuggers"
name = "Affordable Housing and Green Space Equity in Chicago"
members = ["Begum Akkas", "Andrés Camacho", "Evan Fantozzi", "Grace Kluender"]
repo = "uchicago-2025-capp30122/30122-project-treehuggers"
youtube = "jTMRUfCFJLQ"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "wealthspread"
name = "Wealth Spread: Intelligent Portfolio Diversification Tool"
members = ["Shumaila Abbasi", "Khushi Desai", "Marie Farhat", "Raabiyal Ishaq"]
repo = "uchicago-2025-capp30122/30122-project-wealthspread"
youtube = "TODO"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "women-in-stem"
name = "States of Care: Investigating U.S. Maternal Mortality"
members = [
  "Elizabeth Ronan",
  "Dorothy Wongkarnta",
  "Madelin De Jesus Martinez",
  "Alexandrea Harriott",
]
repo = "uchicago-2025-capp30122/30122-project-women-in-stem"
youtube = "TODO"

[[projects]]
date = "2025-03-11"
course = "30122-W25"
slug = "zip-link"
name = "Zip & Link"
members = ["Vyshnavi Voleti", "Nelu Wijegunasekera", "Pragya Khanal"]
repo = "uchicago-2025-capp30122/30122-project-zip-link"
youtube = "O-PwBeorkRI"

[[projects]]
repo = "uchicago-2025-capp30122/30122-project-asia-pacific-enthusiastic-coding-apec"
date = "2025-03-11"
course = "30122-W25"
slug = "apec"
name = "Asia Pacific Enthuastic Coding"
members = ["Tina Dou", "Mauro Ttito", "Ryota Shimizu", "Jose Pajuelo"]
youtube = "QslegtG212E"
